from Tkinter import*
root=Tk()
root.title('HumanFont')
fup=Frame()
size=StringVar()
preview=StringVar()
label1=Label(fup,text='size:')
entry1=Entry(fup,textvariable=size,width=20)
label1.grid(row=1,column=1)
entry1.grid(row=1,column=2)

bt1=Button(fup,text='Preview')
bt4=Button(fup,text='OutputPDF')
bt3=Button(fup,text='Input')
bt2=Button(fup,text='Browse')
label1=Label(fup,text='Preview:')
entry1=Entry(fup,textvariable=preview)

bt1.grid(row=3,column=3)
bt2.grid(row=2,column=1)
bt3.grid(row=2,column=2)
bt4.grid(row=2,column=3)
label1.grid(row=3,column=1)
entry1.grid(row=3,column=2)

fup.pack()
mainloop()